.\"                                      Hey, EMACS: -*- nroff -*-
.TH FNTSD 1 "May 28, 2013" "FreeNest Test Service" "FreeNest"
.SH NAME
fntsd \- Start FreeNest Test Service 
.SH SYNOPSIS
.B fntsd
.SH DESCRIPTION
This command starts the FreeNest Test Service daemon. If you run this command, the fnts service is run as a normal foreground process. You can start the service as a daemon by using \fBsudo service fnts start\fP command
.SH SEE ALSO
.BR fnts (1).
.SH AUTHOR
tmp was written by Scrooge.
.PP
This manual page was written by Scrooge McDuck <scrooge@dolan>,
for the Debian project (and may be used by others).
