#!/bin/sh
set -e
case "$1" in
    configure)
    ln -s /usr/share/pyshared/fntc /usr/lib/python2.6/dist-packages/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    rm -f /usr/lib/python2.6/dist-packages/fntc
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
