#!/bin/sh
set -e

case "$1" in
    
    install|upgrade)
        SERVER_HOME="/var/lib/fnts"
        SERVER_USER="fnts"
        SERVER_NAME="freenest-test-controller"
        SERVER_GROUP="fnts"
        # create user to avoid running server as root
        # 1. create group if not existing
        if ! getent group | grep -q "^$SERVER_GROUP:" ; then
            echo -n "Adding group $SERVER_GROUP.."
            addgroup --quiet --system $SERVER_GROUP 2>/dev/null ||true
            echo "..done"
        fi
        # 2. create homedir if not existing
        test -d $SERVER_HOME || mkdir $SERVER_HOME
        # 3. create user if not existing
        if ! getent passwd | grep -q "^$SERVER_USER:"; then
            echo -n "Adding system user $SERVER_USER.."
            adduser --quiet \
                --system \
                --ingroup $SERVER_GROUP \
                --no-create-home \
                --disabled-password \
                --shell /bin/bash \
                $SERVER_USER 2>/dev/null || true
            echo "..done"
        fi
        # 4. adjust passwd entry
        usermod -c "$SERVER_NAME" \
            -d $SERVER_HOME   \
            -g $SERVER_GROUP  \
            $SERVER_USER

        # 5. create SSH key
        cd $SERVER_HOME
        mkdir .ssh
        cd .ssh
        ssh-keygen -t rsa -N "" -f "fnts"

        # 6. adjust file and directory permissions
        if ! dpkg-statoverride --list $SERVER_HOME >/dev/null
        then
            chown -R $SERVER_USER:$SERVER_USER $SERVER_HOME
            chmod u=rwx,g=rxs,o= $SERVER_HOME
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0

#DEBHELPER#
