#!/bin/sh
set -e
case "$1" in
    remove)
        rm -f /usr/lib/python2.7/dist-packages/fnts
        rm -f /usr/share/pyshared/fnts/*.pyc
    ;;

    upgrade)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0

#DEBHELPER#
